FROM node:21-alpine3.19 AS vue-build-stage
WORKDIR /app
COPY webui/yarn.lock webui/package.json ./
RUN yarn install

COPY webui/ .
RUN yarn run build-prod

FROM nginx:stable

COPY --from=vue-build-stage /app/dist/ /usr/share/nginx/html/
